spring.application.name=Customer-Support-Ticket-Management-System-1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/customer-support-ticket-management-System?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=your-secure-secret-key-1234567890abcdef1234567890abcdef 
jwt.expiration=86400000 
# 1 day in milliseconds 
jwt.refresh.expiration=604800000 